FROM node:22 AS web-build

WORKDIR /src/traccar-web

COPY traccar-web/package*.json ./
RUN npm ci --legacy-peer-deps

COPY traccar-web/ ./
RUN npm run build


FROM eclipse-temurin:25 AS server-build

WORKDIR /src

COPY . .

RUN ./gradlew assemble

RUN mkdir -p /out/conf /out/lib /out/schema /out/templates /out/web \
    && cp target/tracker-server.jar /out/ \
    && cp target/lib/* /out/lib/ \
    && cp schema/* /out/schema/ \
    && cp -r templates/* /out/templates/ \
    && cp setup/traccar.xml /out/conf/ \
    && mkdir -p /out/templates/translations \
    && cp -r traccar-web/src/resources/l10n/* /out/templates/translations/


FROM eclipse-temurin:25-jre

WORKDIR /opt/traccar

COPY --from=server-build /out/ /opt/traccar/
COPY --from=web-build /src/traccar-web/build/ /opt/traccar/web/

RUN mkdir -p /opt/traccar/data /opt/traccar/logs

ENTRYPOINT ["java", "-XX:+ExitOnOutOfMemoryError", "-jar", "tracker-server.jar", "conf/traccar.xml"]
